from pathlib import Path

p = Path('/opt/admin-mct-api/server.js')
s = p.read_text()

schema_marker = 'db.exec(\n  "CREATE TABLE IF NOT EXISTS security_logs (" +\n    "id INTEGER PRIMARY KEY AUTOINCREMENT, " +\n    "admin_id INTEGER NOT NULL, " +\n    "action TEXT NOT NULL, " +\n    "ip_address TEXT, " +\n    "user_agent TEXT, " +\n    "meta_json TEXT, " +\n    "created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP" +\n    ");",\n);\n'

schema_block = '''\n\ndb.exec(\n  "CREATE TABLE IF NOT EXISTS company_info_store (" +\n    "id INTEGER PRIMARY KEY CHECK (id = 1), " +\n    "data_json TEXT NOT NULL DEFAULT '{}', " +\n    "created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, " +\n    "updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP" +\n    ");",\n);\n\ndb.prepare(\n  "INSERT OR IGNORE INTO company_info_store (id, data_json) VALUES (1, ?)"\n).run(\n  JSON.stringify({\n    id: 1,\n    short_name: "MÁY CÔNG TRÌNH NHẬP KHẨU",\n    full_name: "Công Ty Xuất Nhập Khẩu Máy Công Trình",\n    slogan: "Máy Công Trình Chất Lượng Cao",\n    about: "",\n    tax_code: "Đang cập nhật",\n    business_license: "",\n    legal_representative: "",\n    established_year: 2020,\n    phone: "0966121686",\n    hotline: "0966121686",\n    email: "k9dinhthong@gmail.com",\n    contact_email: "k9dinhthong@gmail.com",\n    website: "https://maycongtrinhnhapkhau.com.vn",\n    address: "Số 168 - Khu 4 - Xã Tế Lỗ",\n    map_address: "https://www.google.com/maps",\n    google_map_embed: "",\n    facebook: "https://www.facebook.com/",\n    zalo: "https://zalo.me/0966121686",\n    whatsapp: "",\n    telegram: "https://t.me/sugar88_vr",\n    tiktok: "https://www.tiktok.com/",\n    instagram: "#",\n    youtube: "#",\n    wechat: "https://ehsccjufbaehvfo",\n    logo_url: "/img/Logo/Logo.png",\n    intro_image: "/img/IntroCompany/Company.png",\n    og_image: "/img/Logo/Logo.png",\n    favicon_url: "/img/Logo/Favicon.png",\n    meta_title: "KOBELCO - KOMATSU - HITACHI",\n    meta_description:\n      "Chuyên mua bán máy công trình nhập khẩu, máy xúc, máy đào, máy ủi, phụ tùng và dịch vụ liên quan.",\n    meta_keywords:\n      "máy công trình, máy xúc, máy đào, kobelco, komatsu, hitachi, máy công trình nhập khẩu",\n    copyright_text:\n      "© 2026 Công Ty Xuất Nhập Khẩu Máy Công Trình. All rights reserved.",\n    working_hours: "Thứ 2 - Chủ nhật: 08:00 - 18:00",\n    is_active: 1,\n    created_at: "2026-04-27 14:37:16",\n    updated_at: "2026-04-28 10:58:03",\n    custom_fields: [],\n  }),\n);\n'''

routes_marker = 'app.get("/api/health", (_req, res) => res.json({ ok: true }));\n'

routes_block = '''\napp.get("/api/company-info", requireAuth, (_req, res) => {\n  const row = db\n    .prepare("SELECT data_json FROM company_info_store WHERE id = 1")\n    .get();\n\n  if (!row) {\n    return res.status(404).json({ message: "Không tìm thấy thông tin công ty." });\n  }\n\n  try {\n    const data = JSON.parse(row.data_json || "{}");\n    return res.json(data);\n  } catch {\n    return res.status(500).json({ message: "Dữ liệu company bị lỗi JSON." });\n  }\n});\n\napp.put("/api/company-info", requireAuth, (req, res) => {\n  const body = req.body || {};\n  const shortName = typeof body.short_name === "string" ? body.short_name.trim() : "";\n  const fullName = typeof body.full_name === "string" ? body.full_name.trim() : "";\n  const email = typeof body.email === "string" ? body.email.trim() : "";\n  const phone = typeof body.phone === "string" ? body.phone.trim() : "";\n\n  if (!shortName || !fullName || !email || !phone) {\n    return res.status(400).json({\n      message: "Thiếu các trường bắt buộc: short_name, full_name, email, phone.",\n    });\n  }\n\n  const payload = {\n    ...body,\n    id: 1,\n    short_name: shortName,\n    full_name: fullName,\n    email,\n    phone,\n    is_active: Number(body.is_active) === 0 ? 0 : 1,\n    custom_fields: Array.isArray(body.custom_fields) ? body.custom_fields : [],\n    updated_at: new Date().toISOString().slice(0, 19).replace("T", " "),\n  };\n\n  db.prepare(\n    "UPDATE company_info_store SET data_json = ?, updated_at = CURRENT_TIMESTAMP WHERE id = 1",\n  ).run(JSON.stringify(payload));\n\n  return res.json({ ok: true });\n});\n\n'''

if 'CREATE TABLE IF NOT EXISTS company_info_store' not in s:
  s = s.replace(schema_marker, schema_marker + schema_block)

if 'app.get("/api/company-info", requireAuth' not in s:
  s = s.replace(routes_marker, routes_block + routes_marker)

p.write_text(s)
print('patched-ok')
